### ISSUE TITLE
Handle API outage gracefully

### ISSUE THREAD

**Issue by ahmouse15** [hyperdefined/CustomLauncherRewrite#8]
I think the Toon+ API is just down right now, and so the launcher pops up first with an exception, then with a second box saying the program is unable to contact the API. After closing both pop ups, they re-open every few seconds since the program queries the API again, blocking the user from logging in. 

It's rare to have API outages, so I think just checking whether the API is online when the program launches, and disabling the scheduler if its offline would fix the issue. You can assign this to me if you'd like

P.S. I also made some changes in my fork a while ago (that I forgot about), mainly changing the main window to use a tab system instead of buttons, and also adding a framework to eventually support settings (if wanted). I can send screenshots if you'd like. I also started to work on adding support for Proton on Linux, since it doesn't crash as much and just runs smoother, which is part of the reason I started to add a settings system. If there's any features you want or don't want me to add to a PR, let me know

**Comment by hyperdefined** [comment]
I never got around to fixing this issue and kind of forgot about it. I can go ahead and fix this now. I think checking if the API is down or not when the program launches will work fine.

I saw your fork a bit ago and compiled it myself to see the changes, I like having tabs instead of separate windows. Feel free to make a PR for those changes, since I like them a lot better than what I have now.

**Comment by hyperdefined** [comment]
I released a new version finally to have these fixes (I had some weird issue with tags/releases).

https://github.com/hyperdefined/CustomLauncherRewrite/releases/tag/1.7.1
